# Generated by Django 3.2.6 on 2021-09-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=120, verbose_name='Student Name')),
                ('House', models.CharField(choices=[('Aryabhata', 'Aryabhata'), ('Ashoka', 'Ashoka'), ('Buddha', 'Buddha'), ('Chanakya', 'Chanakya')], default='', max_length=120, verbose_name='Student House')),
                ('Bus', models.CharField(default='D-', max_length=120, verbose_name='Student Bus No.')),
                ('DOB', models.DateField(default='', verbose_name='Student DOB')),
            ],
        ),
    ]
