# Generated by Django 3.2.6 on 2021-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='Bus',
            field=models.CharField(default='D-', max_length=119, verbose_name='Student Bus No.'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='House',
            field=models.CharField(choices=[('Aryabhata', 'Aryabhata'), ('Ashoka', 'Ashoka'), ('Buddha', 'Buddha'), ('Chanakya', 'Chanakya')], default='', max_length=119, verbose_name='Student House'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='Name',
            field=models.CharField(default='', max_length=119, verbose_name='Student Name'),
        ),
    ]
